name: ${project.name}
main: ${bukkit.plugin.main}
version: ${project.version}
author: ${bukkit.plugin.author}
depend: [ProtocolLib]
api-version: 1.13

commands:
  mocar:
    description: mocar command.
    aliases: [car, mcar]