name: ${project.name}
main: ${bukkit.plugin.main}
version: ${project.version}
author: ${bukkit.plugin.author}
depend: [ProtocolLib]
loadbefore: [PocketLifeCore]
api-version: 1.14

commands:
  vehicle:
    description: vehicle command.
    aliases: [car]