name: PocketLifeVehicle
main: dev.sky_lock.pocketlifevehicle.VehiclePlugin
version: 1.3.6
author: sky_lock
depend: [ProtocolLib]
loadbefore: [PocketLifeCore]
api-version: 1.14

commands:
  vehicle:
    description: vehicle command.
    aliases: [car]