name: Update Dependencies
on:
  push:
    paths:
      - "build.gradle.kts"
    branches:
      - dev/1.19
  workflow_dispatch:

jobs:
  build:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Root Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v1.0.0
        with:
          use-gradlew: false
          gradle-build-module: |-
            :
          gradle-build-configuration: |-
            compileClasspath